train_path: "C:/Users/penda/Desktop/Workspace/My_Projects/Pytorch_Tutorial/U-Net_for_Image_Segmentation/2D_Segmentation/erythrocyte_data/train"
val_path: "C:/Users/penda/Desktop/Workspace/My_Projects/Pytorch_Tutorial/U-Net_for_Image_Segmentation/2D_Segmentation/erythrocyte_data/val"


image_size: 256
num_layers: 12
hidden_dim: 768
mlp_dim: 3072
num_heads: 12
dropout_rate: 0.1
num_patches: 256
patch_size: 16
num_channels: 3
